name: Linux Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_with_bazel:
    runs-on: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazel build \:main
